[workspace]
resolver = "2"
members = ["crates/*"]
default-members = ["crates/code2prompt-core", "crates/code2prompt"]

[profile.release]
lto = "thin"
panic = 'abort'
codegen-units = 1

[workspace.dependencies]
anyhow = "1.0.80"
colored = "2.1.0"
indicatif = "0.17.8"
log = "0.4"
num-format = { version = "0.4.4", features = ["with-system-locale"] }
serde_json = "1.0.114"
handlebars = "4.3"
jwalk = "0.8"
termtree = "0.4"
tiktoken-rs = "0.6.0"
ignore = "0.4.22"
inquire = "0.7.1"
regex = "1.10.3"
git2 = { version = "0.18.2", default-features = false, features = [
    "https",
    "vendored-libgit2",
    "vendored-openssl",
] }
once_cell = "1.19.0"
globset = "0.4.15"
pyo3 = { version = "0.23", features = ["extension-module", "abi3-py312"] }
